version: '3.7'

services:
  currency-exchange:
    image: currency-exchange-demo
    mem_limit: 700m
    ports:
      - 8000:8000
    networks:
      - currency-network
    depends_on:
      - netflix-eureka-naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://netflix-eureka-naming-server:8761/eureka
 
  currency-conversion:
    image: currency-conversion-demo
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - netflix-eureka-naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://netflix-eureka-naming-server:8761/eureka
 
  api-gateway:
    image: api-gateway-demo
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - netflix-eureka-naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://netflix-eureka-naming-server:8761/eureka


  netflix-eureka-naming-server:
    image: naming-server-demo
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network:
