version: '3.7'

services:
  currency-exchange:
    build:
      context: ./currency-exchange-service
    image: currency-exchange-demo:0.02
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - netflix-eureka-naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://netflix-eureka-naming-server:8761/eureka
 
  currency-conversion:
    build:
      context: ./currency-conversion-service
    image: currency-conversion-demo:0.02
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - netflix-eureka-naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://netflix-eureka-naming-server:8761/eureka
 
  api-gateway:
    build:
      context: ./netflix-zuul-api-gateway-server
    image: api-gateway-demo:0.02
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - netflix-eureka-naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://netflix-eureka-naming-server:8761/eureka


  netflix-eureka-naming-server:
    build:
      context: ./netflix-eureka-naming-server
    image: naming-server-demo:0.02
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network:
